up:
	docker-compose up -d --build  

up-stage:
	docker-compose -f docker-compose.stage.yml up -d --build 

stop:
	docker-compose stop

stop-stage:
	docker-compose -f docker-compose.stage.yml stop

down:
	docker-compose down

down-stage:
	docker-compose -f docker-compose.stage.yml down

logs:
	docker-compose logs -f

logs-stage:
	docker-compose -f docker-compose.stage.yml logs -f
